### ISSUE TITLE
open content in new tab/window

### ISSUE THREAD

**Issue by gingerbread123** [vadim-frolov/thank-u#40]
in the content list: right click on the title of the article - there is no option to open in new tab/window.
for me personally it's inconvenient. and don't you think that it also decrease freedom for users' behavior?

**Comment by vadim-frolov** [comment]
Agreed, it came out to be a temporary inconvenience because of the new type of content - internal (posted on smarlike) as opposed to external. To be fixed.
Russians prefer to open everything in a new tab, don't they? (e.g. yandex.ru, etc.) Should we take it into account, bearing in mind the loading times of smartlike.org are far from being optimized yet.

**Comment by gingerbread123** [comment]
many people around me open links in new tabs e.g. in order to pospone reading and not to lose the link/article

**Comment by vadim-frolov** [comment]
That was my question. Should we make it default behavior for russian locale?

**Comment by gingerbread123** [comment]
I don't think that it should be linked to any locale. it's a matter of choice limitation for users

**Comment by vadim-frolov** [comment]
Yes, choice for everyone, open in new tab - for russians? Just checked - default behavior at google.ru as well/

**Comment by gingerbread123** [comment]
from my point of view, the similar behavior for all nations)
right click and choose
